name: Getting started
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: List ENV variables
        run: env

      - name: build with Maven
        run: mvn clean install
  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check policy in Windows
        run: |
          echo Here is the Execution Policy!
          Get-ExecutionPolicy

      - name: List ENV variables
        run: env

      - name: build with Maven
        run: mvn clean install
