name: Push

on:
  workflow_run:
    workflows: [ Build and Deploy ]
    types: [ completed ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the Code
      - name: Checkout the Code
        uses: actions/checkout@v3

      # Copy docker-compose file to EC2 Instance
      - name: upload docker-compose and run
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ec2-user
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          source: docker-compose.yml
          target: .

      # Run the docker-compose fil
      #- name: run docker compose file in EC2
      #  run: |
      #    docker-compose -f docker-compose-yml up

