name: Push

on:
  workflow_run:
    workflows: [ Build and Deploy ]
    types: [ completed ]
  workflow_dispatch:
# Global Environment Variables
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: learning-github-actions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the Code
      - name: Checkout the Code
        uses: actions/checkout@v3

      # Copy docker-compose file to EC2 Instance
      - name: upload docker-compose and run
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ec2-user
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          source: docker-compose.yml
          target: .

      # SSH into EC2 and run install docker-compose
      - name: SSH into EC2 and run docker-compose
        run: |
          echo "${{ secrets.AWS_EC2_PRIVATE_KEY }}" > ~/.ec2PrivKey
          chmod 600 ~/.ec2PrivKey
          ssh -o StrictHostKeyChecking=no -i ~/.ec2PrivKey ec2-user@${{ secrets.AWS_EC2_IP }} << EOF
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo docker-compose version
          sudo usermod -a -G docker ec2-user

      # SSH-again and run docker-compose
      - name: SSH again and run docker-compose
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}" && aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY}}"  && aws configure set region "${{ env.AWS_REGION}}" && aws configure set output "text"
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 521221046117.dkr.ecr.us-east-1.amazonaws.com
          sudo docker-compose -f docker-compose.yml up
