name: Getting started
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Look around
        run: |
          echo Folder content:
          ls -la
          sh ./github-actions-script.sh
          
